version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27019:27017"
      
volumes:
  mongodbdata:
    driver: local
